"""Define strict booking creation and confirmation API schemas."""

from datetime import datetime
from decimal import Decimal
from uuid import UUID

from pydantic import BaseModel, ConfigDict, Field


class BookingCreateRequest(BaseModel):
    """Accept only server-authoritative booking selection values."""

    model_config = ConfigDict(extra="forbid", str_strip_whitespace=True)
    movie_id: UUID
    theatre_id: UUID
    seats: list[str]
    payment_method: str


class BookingMovieResponse(BaseModel):
    """Expose the booked movie identity and title."""

    model_config = ConfigDict(extra="forbid")
    id: UUID
    title: str


class BookingTheatreResponse(BaseModel):
    """Expose the booked theatre identity and name."""

    model_config = ConfigDict(extra="forbid")
    id: UUID
    name: str


class BookingConfirmationResponse(BaseModel):
    """Return the durable confirmation generated by the server."""

    model_config = ConfigDict(extra="forbid")
    booking_confirmation_id: str
    movie: BookingMovieResponse
    theatre: BookingTheatreResponse
    seats: list[str]
    total_price: Decimal
    payment_method: str
    booked_at: datetime
